version: "3.8"
services: 
  sharesecret:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    working_dir: /go/src/github.com/ismaelchess/go-share-secret
    volumes: 
      - .:/go/src/github.com/ismaelchess/go-share-secret
    ports: 
      - ${PORT}:${PORT}

  redis:
    image: redis:5-alpine
    command: "redis-server --appendonly yes"
    volumes:
      - /home/ismael/go/src/github.com/ismaelchess/redis/data:/data
    container_name: ${REDIS_HOST}
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
