version: "3.8"
services: 
  sharesecret:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    working_dir: ${WORKING_DIR}
    volumes: 
      - .:${WORKING_DIR}
    ports: 
      - ${PORT}:${PORT}

  redis:
    image: redis:5-alpine
    command: "redis-server --appendonly yes"
    volumes:
      - ${REDIS_DIR}:/data
    ports: 
      - 6379:6379
