version: "3.8"
services: 
  sharesecret:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    working_dir: /go/src/github.com/ismaelchess/go-share-secret
    volumes: 
      - .:/go/src/github.com/ismaelchess/go-share-secret
    links:
      - redis:devredis1      
    ports: 
      - 8080:8080

  redis:
    build: ./dockerfiles/redis
    container_name: devredis1