version: "3.8"
services: 
  sharesecret:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    working_dir: /go/src/github.com/ismaelchess/go-share-secret
    volumes:
      - .:/go/src/github.com/ismaelchess/go-share-secret
    ports: 
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:5-alpine
    command: "redis-server --appendonly yes"
    volumes:
      - ${HOME}/data/redis:/data
    ports: 
      - 6379:6379